### ISSUE TITLE
Processing on Server

### ISSUE THREAD

**Issue by TopperDEL** [The-Unpredictables/ExceptionAnalyzer#21]
I read about this project in the dotnetpro - thanks for that library! It's an awesome idea!

I want to use it on a server, that should handle the exceptions for the clients. But serialising Exceptions is not really possible. Basically you only use these three things during analysis:
- error message
- stacktrace
- ISO language name

Would you like to have a not-exception-based version included, that takes these three values as input parameters and starts analysis on these? This would help me alot with my client-server-infrastructure. Basically it would mean to provide a different AnalyzedException-class, that is not using T und extend the ExceptionService to accept those three values instead of an exception.

If you like the idea, I may prepare a PR.

**Comment by chr0mcom** [comment]
Hi TopperDEL,

Thanks for your feedback and your idea. I'm very pleased that you read my article. 
Regarding your idea, I don't understand the problem of serializing the exception. An exception implements the ISerializable interface and can actually be sent to an API without any problems. Maybe you can describe your problem in more detail so that I can understand it better?

Best regards
Stefan

**Comment by TopperDEL** [comment]
Hm, maybe I was wrong in my assumption. For whatever reason I thought that serialising an exception is a problem. But I did not even try it.
Well - then you can ignore my idea. The only adjustment would be to not only take the language from the CurrentCulture, but to be able to set it externally.

**Comment by TopperDEL** [comment]
Awesome, thanks! Will try asap!
